@startuml
title hier-case

participant Frontend as FE
participant "proxy: mapping" as map
participant "Description Generator" as DG

FE -> map: GET /description-generation/{task_id}
activate FE
activate map
autonumber

loop
    map -> DG: GET /description-generation/{task_id}
    activate DG
    DG --> map: {"errorText": "The data contains hieroglyphs."}
    deactivate DG
    
    break Success Response
        
        map --> FE: generatedDescription.json
    else Bad Response and Attempt >= 3 
        
        map --> FE: К сожалению, мы не смогли обработать ваш запрос
        deactivate FE
        deactivate map
    end
end

@enduml

