@startuml
title main-pipe-desc-gen
autonumber

participant Frontend as FE
participant "proxy: mapping" as map
participant "Description Generator" as DG

FE -> map: POST .../description-generation
activate FE
activate map
map -> map: auth
map -> DG: POST /description-generation
activate DG

alt Success
    DG -->> map: task_id
    map -->> FE: task_id
else Error
    DG -->> map: {"errorText": "The data contains words that are considered unsafe or banned."}
    map -->> FE: {"errorText": "The data contains words that are considered unsafe or banned."}
end

FE -> map: GET .../description-generation/{task_id}
map -> DG: GET /description-generation/{task_id}

alt Success
    DG -->> map: generatedDescription.json
    map -->> FE: generatedDescription.json
else Unsafe or Banned Words
    DG -->> map: {"errorText": "The data contains words that are considered unsafe or banned."}
    map -->> FE: {"errorText": "The data contains words that are considered unsafe or banned."}
else Presence of Hieroglyphs
    DG -->> map: {"errorText": "The data contains hieroglyphs."}
    deactivate DG
    map -->> FE: {"errorText": "The data contains hieroglyphs."}
deactivate map
deactivate FE
end


@enduml
